Change baselines structure
luxteam/jobs_test_maya pull request #152
Opened 2020-08-15 12:35 UTC by Kataderon

* JIRA TICKET
  * https://adc.luxoft.com/jira/browse/STVCIS-303
  * https://adc.luxoft.com/jira/browse/STVCIS-1234
  * https://adc.luxoft.com/jira/browse/STVCIS-1263
* PURPOSE
  * Use new baselines structure
* TECHNICAL STEPS
  * Run 303-test branch in manual job
* RELATED PR'S
  * https://github.com/luxteam/jobs_launcher/pull/69
* REPORTS

2020-09-07 13:11 UTC, Piromancer requested changes

2020-09-07 13:11 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +            for thumb in list(set().union([''], core_config.THUMBNAIL_PREFIXES)):
Мне кажется можно лучше это записать (как минимум убрать обертку в лист, по сету тоже можно проходить. Я бы написал вообще так
for i in set([''] + core_config.THUMBNAIL_PREFIXES):

2020-09-07 13:11 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +                core_config.logging.error("Can't count sync time for " + rpr_json_path)
Возможно стоит как то в отчете отражать то, что не получилось посчитать sync time, сейчас ведь там будет просто пустые поля получается?

2020-09-07 13:14 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
Не понял вопроса

2020-09-07 13:16 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +                core_config.logging.error("Can't count sync time for " + rpr_json_path)
Это не относится к данному pr

2020-09-07 13:16 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
Что будет, если в джобе выбрать NorthStar как движок и запустить группу NorthStar? Я правильно понимаю, что тогда бейзлайны будут взяты не из корректного места? testType это же название группы?

2020-09-07 13:16 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
В этом случае условие ведь не пройдет

2020-09-07 13:17 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
И зачем вообще нужно второе условие?

2020-09-07 13:19 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
Чтобы не хранить несколько копий, да

2020-09-07 13:21 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +                core_config.logging.error("Can't count sync time for " + rpr_json_path)
Понимаю, это я на будущее

2020-09-07 13:22 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +    if args.engine == '2' and not 'NorthStar' in args.testType:
Есть еще гибрид, в таком случае, но там сложнее видимо это будет реализовать так что ок

2020-09-08 07:59 UTC, Piromancer commented
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3683/Test_20Report/
OSX не прошел

2020-09-09 08:48 UTC, Piromancer commented
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3691/Test_20Report/
Нет бейзлайнов

2020-09-09 13:49 UTC, Piromancer submitted a review, later dismissed

2020-09-15 14:57 UTC, merged