Add new status column
luxteam/jobs_test_maya pull request #153
Opened 2020-08-19 14:28 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1264
### Purpose
* Add new status column that contains a reason why test failed or "passed" depending on test status
### Effect of change
* Collect info about group timeouts
* Mark that testcase was finished when script write info about rendered testcase (for track group timeout exceeded issue)
### Related PR's

### Jenkins Builds
* Will be added after release

2020-08-19 14:38 UTC, Kataderon commented on jobs/Scripts/base_functions.py
> +    report['group_timeout_exceeded'] = False
Почему мы не можем определять кончилось ли время по статусу кейса?

2020-08-19 14:43 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +                template['group_timeout'] = group_timeout
Зачем нам это поле?

2020-08-19 14:44 UTC, Kataderon requested changes
Убери изменения jobs launcher'а из pr, пожалуйста

2020-08-19 14:47 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
Думаю, лучше вынести это в config и остальные сообщения об ошибках то же

2020-08-19 14:50 UTC, Kataderon requested changes
Если будет достигнут таймаут группы, то simple render будет убит и код обработки ошибок не выполнится, лучше перенести это в refactor logs (который лучше уже переименовать, там не только логи форматируются)

2020-08-19 15:09 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +    report['group_timeout_exceeded'] = False
Нельзя однозначно сказать по статусу тест кейса, был ли он завершен по таймауту или нет.
Например, в самом начале для всех кейсов создается json файлы с дефолтной информацией. В нем они помечаются, как error. Тогда, если тест кейс даже не будет начат рендериться из-за таймаута, он будет error. В другой ситуации кейс может отрендериться, но неудачно. Тогда он тоже будет error.
Соответственно, в первом случае кейс error из-за таймаута, а во втором - нет.
Я посчитал, что записывать вместе с информацией о отрендеренном кейсе то, что он был завершен, это достаточно наглядный способ отловить таймауты тестовых групп.

2020-08-19 15:10 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +                template['group_timeout'] = group_timeout
QA просили выводить информацию о длине таймаутов в новой колонке: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2389/Test_20Report/AMD_WX7100-Windows/Results/Blender28/Adaptive_Sampling/report.html?searchText=BL28_RS_AS_041

2020-08-19 15:11 UTC, Kataderon commented on jobs/Scripts/base_functions.py
> +    report['group_timeout_exceeded'] = False
В test_cases.json можно узнать статус кейсов: если inprogress, то таймаут на кейсе произошёл, если active, то даже не начал рендерится. Это для случая, когда уже отработал simple render

2020-08-19 15:11 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
> 
> 
> Убери изменения jobs launcher'а из pr, пожалуйста

Я намеренно не удалял изменения jobs launcher, потому что еще необходимо будет запускать прогоны

2020-08-19 15:13 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
Можно создать ветку с нужным jl

2020-08-19 15:19 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
Мне кажется, что выносить сообщения об ошибках в конфиг, это достаточно спорное решение.
Сообщения об ошибках в разных тестовых репозиториях, как правило, отличаются из-за особенностей каждой тулы (например, это сообщение есть только в блендере и майе. В максе оно другое, т.к. там нет ретраев)

2020-08-19 15:20 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
@MagisterDemens что думаешь?

2020-08-19 15:30 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +    report['group_timeout_exceeded'] = False
Согласен, по test_cases.json таймауты для кейсов с inprogress и active статусами можно отловить, но это не сработает в ситуации, которую я описал выше. Я хотел сделать общий способ, по которому однозначно можно будет определить, произошел таймаут или нет

2020-08-25 12:27 UTC, Piromancer approved these changes

2020-08-25 12:37 UTC, MagisterDemens commented on jobs/Scripts/simpleRender.py
> +                    error_message = "Testcase wasn't executed successfully (all attempts were used). Number of tries: {}".format(str(number_of_tries))
Не обязательно, чтобы все данные в конфиге были универсальны для всех тулов. По-моему использование конфиг файла в этом случае вполне оправданно и разумно.

2020-08-25 12:38 UTC, MagisterDemens approved these changes

2020-08-25 19:16 UTC, epozine approved these changes

2020-08-26 14:53 UTC, merged