Invoke retry if test_cases.json is corrupted
luxteam/jobs_test_maya pull request #162
Opened 2020-08-27 14:44 UTC by Kataderon

* JIRA TICKET
  * https://adc.luxoft.com/jira/browse/STVCIS-1435

* REPORTS
  *

2020-09-02 13:28 UTC, epozine commented
Восставливать json пробовать не будешь?

2020-09-02 13:33 UTC, Kataderon commented
> Восставливать json пробовать не будешь?

Если группа уже будет заканчиваться и тогда произойдёт эта ошибка, то времени на рендер может не хватить. Надёжнее будет перезапустить целиком

2020-09-14 10:51 UTC, epozine requested changes

2020-09-14 10:51 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +        group_failed(args, error_windows)
```suggestion
        group_failed(args)
```

2020-09-14 10:51 UTC, epozine commented on jobs/Scripts/simpleRender.py
> -            os.path.join(os.path.abspath(args.output).replace('\\', '/'), 'test_cases.json'))))
Почему удален replace?

2020-09-14 11:02 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> -            os.path.join(os.path.abspath(args.output).replace('\\', '/'), 'test_cases.json'))))
Он не нужен. Мне не удалось воспроизвести проблему, которая решалась этим способом

2020-09-14 11:04 UTC, epozine requested changes

2020-09-14 11:04 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +    rc = main(args)
```suggestion
    rc = main(args, error_windows)
```

2020-09-14 11:04 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +    rc = main(args)
Насколько я вижу у тебя 2 аргумента у main

2020-09-14 11:05 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +    rc = main(args)
Зачем вообще здесь вызов main?

2020-09-14 11:23 UTC, Kataderon commented on jobs/Scripts/simpleRender.py
> +    rc = main(args)
Чтобы пересоздать json'ы для кейсов с error статусом

2020-09-14 17:09 UTC, epozine approved these changes

2020-09-14 17:09 UTC, epozine commented
Сделай еще раз прогон пожалуйста любой

2020-09-16 16:07 UTC, merged