Add skip engine feature
luxteam/jobs_test_maya pull request #164
Opened 2020-09-06 15:06 UTC by Kataderon

## JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-1389

## RELATED PR'S
* 

## REPORTS

2020-09-10 10:05 UTC, Piromancer requested changes
Нет отчетов, нужны примеры

2020-09-11 08:49 UTC, Piromancer commented
Как проскипать, например, NorthStar?

2020-09-11 08:50 UTC, Kataderon commented
> Как проскипать, например, NorthStar?
Так, как ты сам описал в тикете, только название движка должно быть такое, как в коде

2020-09-14 10:16 UTC, Piromancer approved these changes

2020-09-14 10:28 UTC, epozine approved these changes

2020-09-14 10:29 UTC, merged