Add retries as param
luxteam/jobs_test_maya pull request #165
Opened 2020-09-07 13:33 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1500

## RELATED PR'S
https://github.com/luxteam/jobs_test_blender/pull/113

## REPORTS

2020-09-10 10:04 UTC, Piromancer requested changes
Нет отчетов

2020-09-17 20:49 UTC, epozine submitted a review, later dismissed

2020-09-21 11:30 UTC, epozine submitted a review, later dismissed

2020-09-21 11:59 UTC, MagisterDemens approved these changes

2020-09-21 17:31 UTC, epozine approved these changes

2020-09-24 13:42 UTC, Piromancer commented
https://rpr.cis.luxoft.com/job/viewer_retries/11/Test_20Report/
Не запускается группа

2020-09-24 15:15 UTC, Piromancer approved these changes

2020-09-24 15:16 UTC, epozine approved these changes

2020-09-25 08:17 UTC, merged