Extend skip param
luxteam/jobs_test_maya pull request #192
Opened 2020-09-30 16:12 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1633

## NOTES FOR REVIEWERS

## RELATED PR'S
https://github.com/luxteam/jobs_test_blender/pull/133

## REPORTS

2020-09-30 18:19 UTC, Piromancer commented
Можешь, пожалуйста, написать пример как скипнуть, к примеру, кейс на OSX если выбран NorthStar?

2020-10-01 07:47 UTC, Kataderon commented
> Можешь, пожалуйста, написать пример как скипнуть, к примеру, кейс на OSX если выбран NorthStar?


        "skip": [
            ["AMD Radeon RX Vega 56 (Metal)", "Northstar"]
        ]

2020-10-01 13:55 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3806/Test_20Report/
Не скипаются тесты на гибриде. Для сравнения, вот та же группа на мастере https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3808/Test_20Report/

2020-10-01 14:12 UTC, Kataderon commented
> https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3806/Test_20Report/
> Не скипаются тесты на гибриде. Для сравнения, вот та же группа на мастере https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3808/Test_20Report/

Потому что skip оформлен неправильно. Команда qa может сама указать нужные параметры для пропуска тестов? Пример я написал выше. Я не знаю в каких случаях должны указываться операционные системы, движки и карты

2020-10-07 16:15 UTC, epozine commented
Какой статус у данного ПРа?

2020-10-09 16:15 UTC, Kataderon commented
> Какой статус у данного ПРа?

Жду ответа от qa команды

2020-10-27 10:08 UTC, closed without merging