Marking expected black images for RPRMayaPlugin
luxteam/jobs_test_maya pull request #193
Opened 2020-09-30 18:18 UTC by PossessedKeepo

- TRELLO TICKET
https://trello.com/c/wI7AmJV9/140-marking-expected-black-images

- PURPOSE
To mark all expected black images for RPRMayaPlugin

- NOTES FOR REVIEWERS
Done with Maya

2020-10-01 07:45 UTC, Kataderon requested changes
Убери изменения jobs launcher

2020-10-07 11:04 UTC, Piromancer approved these changes

2020-10-07 11:05 UTC, PossessedKeepo commented
Убрал изменения jobs_laucnher, закончил со всеми пометками

2020-10-07 13:53 UTC, Kataderon approved these changes

2020-10-07 16:15 UTC, merged