Add python script into local reports
luxteam/jobs_test_maya pull request #274
Opened 2021-01-12 08:23 UTC by Flame0n

### **Jira Ticket** 

- https://adc.luxoft.com/jira/browse/STVCIS-1797

### **Purpose**

- Add reprot "functions" fields form test_cases.json

### **Jenkins Builds**

- https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4263/

2021-01-12 09:36 UTC, Speedwag00n submitted a review, later dismissed

2021-01-12 09:51 UTC, Piromancer requested changes
В таком виде это не юзаемо, можешь, пожалуйста, парсить строчки? Например, если в json-е написано так:
'functions': [
"if not cmds.pluginInfo('fbxmaya', query=True, loaded=True): cmds.loadPlugin('fbxmaya', quiet=True)", 
'mel.eval(/'FBXImport -f ("/' + RES_PATH + /'" + "/Smoke/default/park_bench1.fbx")/')', 
'rpr_render(case)', 
"cmds.delete('Default')"
]

то в поле должно быть
if not cmds.pluginInfo('fbxmaya', query=True, loaded=True): cmds.loadPlugin('fbxmaya', quiet=True)
mel.eval(/'FBXImport -f ("/' + RES_PATH + /'" + "/Smoke/default/park_bench1.fbx")/')
rpr_render(case)
cmds.delete('Default')

Таким образом можно просто скопировать код в тулу

2021-01-13 09:33 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4291/

2021-01-13 10:10 UTC, Speedwag00n approved these changes

2021-01-13 12:49 UTC, Piromancer approved these changes

2021-01-13 12:50 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/

2021-01-14 08:28 UTC, closed without merging