Select GUI or batch render for each group
luxteam/jobs_test_maya pull request #281
Opened 2021-01-31 20:46 UTC by NISHIY-EKSDEE

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1885
## PURPOSE
Add the possibility to select batch render or GUI rendering for each group
## EFFECT OF CHANGE
Additional `base_functions_batch.py` file
Additional `test_cases_batch.json` file for each group (if batch render is supported)
Additional `--batchRender` parameter for `simpleRender` (can be ignored, `false` by default)
Some additional logic in `simpleRender.py` for batch render support
Move `event` function to a separate `event_recorder.py` file in order to register `Open tool` and `Close tool` events via terminal to count its time correctly.
## NOTES FOR REVIEWERS
There are additional fileds in `test_cases_batch.json`:
- `camera` - to select renderable camera
- `functions_before_render` - to apply case's functions in preRender section, if there are not working in preFrame section, so case will render separately with its individual `Render` command. (maybe it should be renamed)
- `frame_number` - to select desired frame for case. Works the same as `functions_before_render`, but with additional `-s` parameter for `Render` command, because setting frame number using `current_time` doesn't work in preFrame section. Maybe there is some solution that i haven't found

`extract_img_from` is an additional function in `base_functions_batch` to get images from subdirectories for cases with AOVs. It is used in case functions.

2021-02-03 08:44 UTC, Piromancer requested changes
1. Хотелось бы ссылку на прогон с веткой, иначе вообще не могу сказать работает ветка или нет
2. Клонирование base_functions.py и всех test_cases.json мне кажется абсолютно излишним. Поддерживать в два раза больше файлов никто не будет.
3. Многое в base_functions_batch.py меня смущает. Например функция rpr_render не соответствует названию (там производится валидация файлов). В enable_rpr передается case, но нигде не используется.  Остались закомментированные строчки кода.
4. Зачем был создан event_recorder.py?
5. Почти уверен, что изменения в run.sh, run.bat ломают не-батч режим

2021-02-03 08:46 UTC, epozine commented
> 1. Хотелось бы ссылку на прогон с веткой, иначе вообще не могу сказать работает ветка или нет
> 2. Клонирование base_functions.py и всех test_cases.json мне кажется абсолютно излишним. Поддерживать в два раза больше файлов никто не будет.
> 3. Многое в base_functions_batch.py меня смущает. Например функция rpr_render не соответствует названию (там производится валидация файлов). В enable_rpr передается case, но нигде не используется.  Остались закомментированные строчки кода.
> 4. Зачем был создан event_recorder.py?
> 5. Почти уверен, что изменения в run.sh, run.bat ломают не-батч режим

Про 2 пункт скажу, что это вынужденая мера. Далее на ваше усмотрение какой режим использовать и поддерживать

2021-02-03 09:00 UTC, Piromancer commented
Камеру и фрейм кстати можно парсить из сцены, а значит почти все test_cases_batch.json не нужны. А кейсы с AOV можно обработать особым образом в какой-нибудь функции пост рендера к примеру. Таким образом не уверен, что без них нельзя обойтись. Если я что-то забываю, поправьте меня. Кадр и камеру можно найти в .ma файле, если будет нужно я могу сказать как

2021-02-03 10:24 UTC, NISHIY-EKSDEE commented
> 1. Хотелось бы ссылку на прогон с веткой, иначе вообще не могу сказать работает ветка или нет
> 2. Клонирование base_functions.py и всех test_cases.json мне кажется абсолютно излишним. Поддерживать в два раза больше файлов никто не будет.
> 3. Многое в base_functions_batch.py меня смущает. Например функция rpr_render не соответствует названию (там производится валидация файлов). В enable_rpr передается case, но нигде не используется.  Остались закомментированные строчки кода.
> 4. Зачем был создан event_recorder.py? Без него точно никак?
> 5. Почти уверен, что изменения в run.sh, run.bat ломают не-батч режим
> 6. Параметр functions_before_render учитывает, что после вызова rpr_render последующие строчки обычно возвращают сцену в изначальное состояние?

1. Сейчас запустил билд, заодно посмотрю макОС, т.к. до этого не было возможности потестить на нем
2/3. Изначально не планировалось совмещение режимов, поэтому подогнал функции под существующие `test_cases` с `rpr_render` в каждом кейсе. `test_cases_batch` остались с моих исследований групп, в принципе, можно оставить этот файл только там, где батч рендер нужен. В `enable_rpr` `case` передается в функцию `event`. Комментарии уберу.
4. Сейчас в мастере события `Open tool` и `Close tool` вызываются единожды в `simple_render`, так как Майя запускается один раз. При батч рендере процесс Render запускается несколько раз и тула, соответственно, загружается и выгружается несколько раз. Поэтому я регистрирую эти события через терминал перед и после Render каждый раз
5.  На винде точно не ломается. Жду прогон для подтверждения.
6. Внутри `base_functions_batch` все функции после `rpr_render` применяются после рендера

Подумаю как совместить файлы `base_functions` в один.
Фрейм и камеру указываю явно, так как если брать каждый кейс за фрейм (а-ля анимация из кейсов), то вызывать функции отдельно для каждого кейса можно только в preFrame секции, но изменение камеры или фрейма не применяются на этой стадии, поэтому я запускаю процесс Render с этими параметрами в терминале.

Вообще я не уверен насчет режима "анимации", так как он сильно усложняет логику. Изначально я его сделал, чтобы уменьшить количество запусков процесса Render, так как запуск очень долгий (~10 секунд на SSD, ~30 секунд на HDD), но многие функции не применяются в `preFrame`, поэтому большинство кейсов все равно запускается с параметром `functions_before_render` отдельно.

2021-02-03 14:10 UTC, NISHIY-EKSDEE commented
Прогон регрессии
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4416/Test_20Report/

2021-02-04 12:48 UTC, Piromancer commented
> Прогон регрессии
> https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4416/Test_20Report/

А есть такой же прогон с батч рендерингом?

2021-02-04 13:01 UTC, Piromancer commented
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4416/Test_20Report/Northstar/AMD_RX5700XT-Windows-regression.json~/Results/Maya/Anti_Aliasing/render_tool_logs/MAYA_RS_AA_005.log
 >>> [RPR TEST] [12:36:39] Error "string indices must be integers" with string "rpr_render(case)"
 Такого раньше не видел, посмотришь?

2021-02-07 18:46 UTC, NISHIY-EKSDEE commented
> 
> 
> https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4416/Test_20Report/Northstar/AMD_RX5700XT-Windows-regression.json~/Results/Maya/Anti_Aliasing/render_tool_logs/MAYA_RS_AA_005.log
> 
> [RPR TEST] [12:36:39] Error "string indices must be integers" with string "rpr_render(case)"
> Такого раньше не видел, посмотришь?

Моя ошибка в коде, уже исправил.

Старый прогон регрессии только на батч рендере
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4236/Test_20Report/

Полный прогон всех групп, которые сейчас отмечены для батч рендера. С ошибками на маке сейчас разбираюсь
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4432/Test_20Report/

2021-03-06 18:53 UTC, NISHIY-EKSDEE commented
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4556/
Animation, PBR, Smoke запускались в графическом режиме, остальные в батче.
Error'ы на маке связаны с зависанием  батча, когда используется Northstar. Когда локально тестировал на маке, чаще вылетают сообщения об ошибке от процесса senddmp, которые быстро отлавливаются. Но иногда процесс просто зависает, и это можно отследить только по таймауту. Лучше всего видно на IBL, там Майя пару раз так зависла и приходилось ждать по 4 минуты, поэтому группа не успела отработать до конца

2021-03-12 13:50 UTC, Piromancer commented
Мне все же не понятно зачем нам дублировать все test_cases.json. В большинстве случаев они полностью идентичны оригинальным файлам, а группы в которых это играет какую-то роль на батче гонятся не будут (если только в каком-то исключительном случае). Давайте уберем это дублирование, а все остальное мне нравится

2021-03-26 15:39 UTC, Speedwag00n requested changes

2021-03-26 15:39 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> -    cmds.setAttr('defaultRenderGlobals.currentRenderer',
Все ли будет ок без выставления этого аттрибута?

2021-03-26 15:39 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +    parser.add_argument('--batchRender', required=False, default=False, type=str2bool)
Т.к. тут уже задано дефотлное значение + параметр необязательный, можно было не добавлять этот параметр прямо во все файлы

2021-03-26 15:39 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +    copyfile(os.path.join(os.path.dirname(__file__), 'event_recorder.py'), os.path.join(args.output, 'event_recorder.py'))
Не понял, зачем скрипт копируется

2021-03-26 15:39 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +        event('Postrender', True, case['case'])
Тут должен быть Prerender + ее лучше вынести после if-блока. Тогда ивент будет закрытым в случаях и бача, и UI

2021-03-28 15:07 UTC, NISHIY-EKSDEE commented on jobs/Scripts/base_functions.py
> -    cmds.setAttr('defaultRenderGlobals.currentRenderer',
Вернул, все работает. Без этой строчки скорее всего берется настройка из сцены

2021-03-28 15:14 UTC, NISHIY-EKSDEE commented on jobs/Scripts/simpleRender.py
> +    copyfile(os.path.join(os.path.dirname(__file__), 'event_recorder.py'), os.path.join(args.output, 'event_recorder.py'))
Я выносил функцию event в отдельный скрипт, чтобы регистрировать события открытия/закрытия тулы при батче. Т.к. в графическом режиме тула открывается и закрывается один раз, это делается в launchMaya
https://github.com/luxteam/jobs_test_maya/blob/vastrakhantsev/select_batch_or_gui_mode/jobs/Scripts/simpleRender.py#L262
https://github.com/luxteam/jobs_test_maya/blob/vastrakhantsev/select_batch_or_gui_mode/jobs/Scripts/simpleRender.py#L334 
В батче события надо регистрировать между каждым запуском

2021-03-28 15:22 UTC, NISHIY-EKSDEE commented on jobs/Scripts/base_functions.py
> +        event('Postrender', True, case['case'])
В этом if блоке запускается рендер в UI, а потом начинается Postrender. При батче рендер начинается после этой функции и Postrender начинается в функции postrender

2021-03-29 05:46 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +    copyfile(os.path.join(os.path.dirname(__file__), 'event_recorder.py'), os.path.join(args.output, 'event_recorder.py'))
Нужно тогда добавить краткие комментарии в скрипте, почему при UI рендере одна имплементация, при батче - другая

2021-03-29 05:58 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +        event('Postrender', True, case['case'])
Prerender еще раз посмотрел. Там все ок, необратил внимание
Появились другие вопросы:
1. Ивент Postrender дважды открывается по итогу для UI. Один раз в rpr_render, другой в postrender
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L185
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L195
2. Вроде бы нигде не вызывается postrender. https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L189
3. ИвентClose tool дважды открывается, но нигде не закрывается
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L195
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L372
4. Ивент Open tool закрывается, но нигде не открывается
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/base_functions.py#L339

2021-03-29 07:35 UTC, NISHIY-EKSDEE commented on jobs/Scripts/simpleRender.py
> +    copyfile(os.path.join(os.path.dirname(__file__), 'event_recorder.py'), os.path.join(args.output, 'event_recorder.py'))
Для UI этот же скрипт используется. По сути это та же функция, что была раньше в base_functions, только я добавил возможность вызывать ее из консоли с параметрами

2021-03-29 07:50 UTC, NISHIY-EKSDEE commented on jobs/Scripts/base_functions.py
> +        event('Postrender', True, case['case'])
1-2. postrender для UI не вызывается, он вызывается только в батче в параметре -postRender
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/simpleRender.py#L372
Для соблюдения логики можно сделать вызов postrender для UI, там же регистрировать ивент

3. Ивент Close tool должен заканчиваться после того, как закроется Майя, соответственно его невозможно закрыть в base_functions, поэтому он закрывается в simpleRender.
При батче после каждого рендера, т.к. мы постоянно перезапускаем тулу
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/simpleRender.py#L371-L384
И последний раз в launchMaya, чтобы для UI ивент тоже закрылся
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/simpleRender.py#L334
4. Аналогично 3 пункту
Первый раз ивент открывается в launchMaya и для UI, и для батча
https://github.com/luxteam/jobs_test_maya/blob/cafc444edb7fa942e219c70bd53bc4eca7b6f9bf/jobs/Scripts/simpleRender.py#L262
При батче он потом открывается перед каждым запуском

2021-03-30 08:11 UTC, NISHIY-EKSDEE commented
Полный прогон
[Full](https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4666/)
На маке по непонятной причине провалились группы Support_2018, Support_2019. При перезапуске все отработало нормально
[Support_2018/2019](https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4671/)

2021-04-01 12:20 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +        event('Postrender', True, case['case'])
Запутанная система с ивентами сейчас получается. Нужно будет потом запланиваро небольшую задачу, в которой опишем ивенты в каждой репе
Апрув поставил

2021-04-01 12:20 UTC, Speedwag00n approved these changes

2021-04-07 07:56 UTC, Piromancer approved these changes

2021-04-07 09:18 UTC, merged