Python39
luxteam/jobs_test_maya pull request #314
Opened 2021-03-25 09:21 UTC by Flame0n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1360
### Purpose
* Migrate to python 3.9
### Related PR'S
* https://github.com/luxteam/jobs_launcher/pull/171
### Jenkins Builds

2021-03-26 13:40 UTC, Speedwag00n commented
Так, только на этом ПРе озадачился вопросом, где билды

2021-03-26 13:41 UTC, Speedwag00n requested changes
Добавь, пожалуйста, ссылку на билд

2021-04-07 14:30 UTC, Speedwag00n submitted a review, later dismissed

2021-04-07 14:31 UTC, Speedwag00n commented
Нужно конфликт решить

2021-04-07 14:35 UTC, Speedwag00n approved these changes

2021-04-07 15:52 UTC, epozine approved these changes

2021-04-07 15:56 UTC, merged