System monitor
luxteam/jobs_test_maya pull request #326
Opened 2021-05-24 08:28 UTC by NISHIY-EKSDEE

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-2273
https://adc.luxoft.com/jira/browse/STVCIS-2274
## PURPOSE
Read metrics while tests
Analyze it in future
## EFFECT OF CHANGE
System monitor process launch before tests launch.
Directory with metrics inside of group's directory
Saving start and end time for each case in test cases and report
## RELATED PR'S
https://github.com/luxteam/jobs_launcher/pull/192

2021-06-05 11:58 UTC, Speedwag00n requested changes
Изменения сабмодуля лучше не добавлять в ПР. Для тестирования можно создать отдельную ветку с измененным сабмодулем, для которой не будет создаваться ПР

2021-06-05 11:58 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +        test_time = (end_time - datetime.datetime.strptime(case['start_time'], '%Y-%m-%d %H:%M:%S.%f')).total_seconds()
Переменная test_time должна содержать только время вызова команды рендера
Такая реализация будет захватывать еще время prerender. Можно просто оставить вариант из мастера

2021-06-09 08:03 UTC, NISHIY-EKSDEE commented on jobs/Scripts/base_functions.py
> +        test_time = (end_time - datetime.datetime.strptime(case['start_time'], '%Y-%m-%d %H:%M:%S.%f')).total_seconds()
Сделал отдельные отметки времени для всего кейса и рендера, сейчас test_time считается как в мастере

2021-06-09 08:04 UTC, NISHIY-EKSDEE commented
> Изменения сабмодуля лучше не добавлять в ПР. Для тестирования можно создать отдельную ветку с измененным сабмодулем, для которой не будет создаваться ПР

Сабмодуль переключил на мастер

2021-06-09 09:37 UTC, Speedwag00n submitted a review, later dismissed

2022-01-20 10:13 UTC, NISHIY-EKSDEE commented
Билд с разными ОСями и карточками. Kingston с 7100 еще собирал метрики с afterburner. На маках упала группа из-за бага.
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/5320/

Здесь уже есть фикс. Image size упал по таймауту
https://rpruser:cis.report@cis.nas.luxoft.com/RadeonProRenderMayaPluginManual/5344/Test_Report_Northstar/test_report.html

2022-01-20 11:13 UTC, Speedwag00n approved these changes

2022-01-28 07:03 UTC, merged