GUI cache building + engine option
luxteam/jobs_test_maya pull request #331
Opened 2021-06-08 22:33 UTC by NISHIY-EKSDEE

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-2349
https://adc.luxoft.com/jira/browse/STVCIS-2294
## PURPOSE
- Replace batch render cache building
- Use chosen engine to avoid failed Northstar cache building ruin every Tahoe group
## NOTES FOR REVIEWERS
`templog` contains script editor log for rendered scene
## RELATED PR'S
https://github.com/luxteam/rpr_pipelines/pull/633
## REPORTS
https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4929/

2021-06-09 09:23 UTC, Speedwag00n requested changes

2021-06-09 09:23 UTC, Speedwag00n commented on scripts/build_rpr_cache.bat
> +type %MAYA_CMD_FILE_OUTPUT%
Можно передавать относительный путь до того места, где будет лежать лог в конечном итоге
Тогда не нужно будет печатать его в этом скрипте и перенаправлять поток вывода в другой файл в пайплайне

2021-06-09 19:55 UTC, NISHIY-EKSDEE commented on scripts/build_rpr_cache.bat
> +type %MAYA_CMD_FILE_OUTPUT%
При перенаправлении потока в лог попадают сообщения самих скриптов + текст из окна output, которое появляется при запуске Майи (там есть информация про рендерер, видеокарту и т.д.). MAYA_CMD_FILE_OUTPUT задает файл для сообщений из script editor. 
Если указать тот же лог, в который перенаправляем, то сообщения из script editor не сохранятся. 
Если не перенаправлять, а просто передать файл и его указать как MAYA_CMD_FILE_OUTPUT, то потеряются сообщения из консоли (они будут выведены в лог дженкинса). По-разному пытался решить, чтобы ничего не потерять

2021-06-15 07:37 UTC, epozine requested changes
На маках в логе есть сообщение 'successfully uploaded data to AWS!'
Это означает, что у нас отправляются данные Афины. Это нужно отключить для кеша.
На вин10 я этого в логе не увидел.

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +import os
Импорты должны быть сгруппированы в следующем порядке:

импорты из стандартной библиотеки
импорты сторонних библиотек
импорты модулей текущего проекта

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +            print("Plugin not loaded, try to load...")
Было бы неплохо как-то выделить наши собственные сообщения в логе. Например добавить [INFO] по аналогии с пайплайнами. Так будет проще заметить их.

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +            print("Plugin not loaded, try to load...")
```suggestion
            print("[INFO] RadeonProRender plugin is not loaded. Loading RPR plugin ...")
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +        print("Error during plugin load. {}".format(str(err)))
```suggestion
        print("[ERROR] Failed to load RadeonProRender plugin. Error message: {}".format(str(err)))
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +    print("Plugin has been loaded")
```suggestion
    print("[INFO] RadeonProRender plugin has been successfully loaded.")
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +        print("Preparation for rendering")
```suggestion
        print("[INFO] Preparing configurations for rendering...")
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +        print("Render has been finished")
```suggestion
        print("[INFO] Render has been finished")
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +        print("Error during rendering. {}".format(str(err)))
```suggestion
        print("[ERROR] Failed to render the scene. Error message: {}".format(str(err)))
```

2021-06-15 07:37 UTC, epozine commented on jobs/Scripts/cache_building.py
> +        print("Quit")
```suggestion
        print("[INFO] Closing Maya.")
```

2021-06-15 08:11 UTC, Speedwag00n submitted a review, later dismissed

2021-06-15 11:49 UTC, epozine approved these changes

2021-06-15 11:54 UTC, merged